"""
script_B_mu_HEI_v3.py
=====================
Compute per-atom chemical potentials in the HEI product Pt3(Ga,In,Sn,Zn)
using a CEF sublattice regular-solution model fitted to Panel g's 165
UMA composition-energy data points.

v3 change vs v2
----------------
v2 used literature calorimetric ?H_f values (Kumar 1996, Srikanth 1993,
Watson-Hayes 1995, Liu 2011) and Miedema-derived sublattice Omega_ij.
v3 replaces BOTH with values derived from Panel g's UMA data:
  - End-member ?H_f: read directly from the 4 pure-binary rows
  - Omega_ij^sub: least-squares fitted to all 165 data points

This ensures internal consistency between Panel a (chemical potentials)
and Panel g (composition-energy landscape).

CEF sublattice model
--------------------
  alpha (3 sites / f.u.): Pt only, y_Pt^alpha = 1
  beta  (1 site  / f.u.): Ga/In/Sn/Zn mix, y_i^beta variable

Per atom of formula unit (= per atom of alloy):
  dH_f(y) = Sum_i y_i * h_i + Sum_{i<j} w_ij * y_i * y_j

  h_i = ElementRef_Hf_kJ_mol for pure Pt3Xi (from 165-pt CSV)
  w_ij = sublattice interaction parameter (fitted)

Chemical potential (per atom, 0K):
  beta element k: mu_k = h_k + Sum_{j!=k} w_kj * y_j - Sum_{i<j} w_ij * y_i * y_j
  Pt (alpha):     mu_Pt = Sum y_i h_i + G^xs  (= G_atom, Gibbs-Duhem consistent)

Data source
-----------
  Panel g 165-point CSV:
    data_FigG_165_ElementReferenced_Hf.csv
    Units: kJ/mol per atom, element-referenced (SER convention)
    Generated by 20260417_FigG_ElementReference_Rebuild.py from UMA energies

Outputs (all in ../outputs/)
-----------------------------
  mu_HEI_v3_0K.csv             Main Panel a end-points
  mu_HEI_v3_T_table.csv        SI temperature table
  omega_beta_subl_v3_fit.csv    Fitted Omega parameters + quality
  cef_fit_v3_quality.csv        R-squared, RMSE, parity data
  beta_diffusion_potentials_v3_0K.csv
                                Gauge-invariant beta-sublattice exchange
                                potentials relative to Ga
  beta_diffusion_potentials_v3_T_table.csv
                                Temperature-dependent exchange potentials
  script_B_v3_meta.json

Author: 2026-04-23 v3
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ELEMENTS: list[str] = ["Ga", "In", "Sn", "Zn"]
PAIRS: list[tuple[str, str]] = [
    ("Ga", "In"), ("Ga", "Sn"), ("Ga", "Zn"),
    ("In", "Sn"), ("In", "Zn"), ("Sn", "Zn"),
]

Y_BETA: dict[str, float] = {"Ga": 0.65, "In": 0.20, "Sn": 0.10, "Zn": 0.05}
R_KJ: float = 8.31446261815324e-3
SI_TEMPERATURES: list[int] = [300, 800, 1000, 1200]


def _resolve_data_csv() -> Path:
    """Locate data_FigG_165_ElementReferenced_Hf.csv inside the release tree."""
    script_dir = Path(__file__).resolve().parent          # scripts/
    panel_e_dir = script_dir.parent                       # Panel_e_ChemicalPotentialCascade/
    release_root = panel_e_dir.parent                     # code_release_v2/
    csv = (release_root / "SI_Figures"
           / "SI_Fig04_165CompositionLandscape"
           / "data_FigG_165_ElementReferenced_Hf.csv")
    if not csv.exists():
        raise FileNotFoundError(f"Cannot find 165-pt CSV at {csv}")
    return csv


def fit_cef(df: pd.DataFrame) -> tuple[dict[str, float], np.ndarray, dict]:
    """Fit CEF sublattice regular-solution model to 165-point data.

    Returns
    -------
    h_end : dict   end-member dH_f per atom (kJ/mol per atom)
    omega : array  6 fitted w_ij values (per atom)
    quality : dict  R-squared, RMSE, etc.
    """
    for el in ELEMENTS:
        df[f"y_{el}"] = df[f"{el}_count"] / 8.0

    h_end: dict[str, float] = {}
    for el in ELEMENTS:
        mask = df[f"{el}_count"] == 8
        h_end[el] = float(df.loc[mask, "ElementRef_Hf_kJ_mol"].values[0])

    endmember_linear = sum(df[f"y_{el}"] * h_end[el] for el in ELEMENTS)
    b = (df["ElementRef_Hf_kJ_mol"] - endmember_linear).values

    A = np.column_stack([
        df[f"y_{ei}"].values * df[f"y_{ej}"].values
        for ei, ej in PAIRS
    ])

    omega, _, _, _ = np.linalg.lstsq(A, b, rcond=None)

    y_pred = A @ omega + endmember_linear.values
    y_data = df["ElementRef_Hf_kJ_mol"].values
    ss_res = float(np.sum((y_data - y_pred) ** 2))
    ss_tot = float(np.sum((y_data - y_data.mean()) ** 2))
    R2 = 1.0 - ss_res / ss_tot
    RMSE = float(np.sqrt(ss_res / len(df)))
    max_err = float(np.max(np.abs(y_data - y_pred)))

    quality = {
        "R2": round(R2, 6),
        "RMSE_kJmol_atom": round(RMSE, 4),
        "max_abs_error_kJmol_atom": round(max_err, 4),
        "n_data": len(df),
        "n_params": len(PAIRS),
    }
    return h_end, omega, quality


def _omega_lookup(omega: np.ndarray) -> dict[tuple[str, str], float]:
    d: dict[tuple[str, str], float] = {}
    for idx, (ei, ej) in enumerate(PAIRS):
        d[(ei, ej)] = omega[idx]
        d[(ej, ei)] = omega[idx]
    return d


def mu_HEI_per_atom(
    y: dict[str, float],
    h_end: dict[str, float],
    omega: np.ndarray,
    T: float,
) -> list[dict]:
    """Chemical potentials (per atom, SER ref) for 5 elements at given T."""
    om = _omega_lookup(omega)

    G_xs = sum(omega[idx] * y[ei] * y[ej] for idx, (ei, ej) in enumerate(PAIRS))
    G_atom = sum(y[el] * h_end[el] for el in ELEMENTS) + G_xs

    rows: list[dict] = []

    for el in ELEMENTS:
        h_i = h_end[el]
        excess = (sum(om.get((el, ej), 0.0) * y[ej]
                      for ej in ELEMENTS if ej != el) - G_xs)
        entropy = (R_KJ * T * np.log(y[el]) / 4.0) if T > 0 else 0.0
        mu = h_i + excess + entropy
        rows.append({
            "element": el,
            "sublattice": "beta",
            "y_i": y[el],
            "h_endmember_per_atom_kJmol": round(h_i, 4),
            "excess_per_atom_kJmol": round(excess, 4),
            "entropy_per_atom_kJmol": round(entropy, 4),
            "mu_HEI_per_atom_kJmol": round(mu, 4),
            "note": f"beta: Pt3{el} UMA end-member + CEF excess",
        })

    entropy_Pt = 0.0
    mu_Pt = G_atom + entropy_Pt
    rows.append({
        "element": "Pt",
        "sublattice": "alpha",
        "y_i": 1.0,
        "h_endmember_per_atom_kJmol": round(sum(y[el] * h_end[el]
                                                 for el in ELEMENTS), 4),
        "excess_per_atom_kJmol": round(G_xs, 4),
        "entropy_per_atom_kJmol": 0.0,
        "mu_HEI_per_atom_kJmol": round(mu_Pt, 4),
        "note": "alpha: G_atom (Gibbs-Duhem consistent)",
    })
    return rows


def beta_diffusion_potentials(
    rows: list[dict], reference: str = "Ga", T: float | None = None
) -> list[dict]:
    """Return gauge-invariant beta-site exchange potentials.

    The fitted free energy is expressed per alloy atom, q(y). Because one
    beta site occurs per four-atom Pt3X formula unit, an elemental exchange
    chemical potential is

        mu_i - mu_ref = 4 * (dq/dy_i - dq/dy_ref).

    Absolute elemental chemical potentials cannot be identified uniquely
    from the fixed-Pt3X composition manifold alone.
    """
    beta = {
        row["element"]: float(row["mu_HEI_per_atom_kJmol"])
        for row in rows
        if row["sublattice"] == "beta"
    }
    if reference not in beta:
        raise ValueError(f"Reference element {reference!r} is not on the beta sublattice")

    output = []
    for element in ELEMENTS:
        normalized_difference = beta[element] - beta[reference]
        row = {
            "element": element,
            "reference_element": reference,
            "normalized_CEF_difference_kJmol_alloy_atom": round(
                normalized_difference, 4
            ),
            "diffusion_potential_kJmol_element": round(
                4.0 * normalized_difference, 4
            ),
            "definition": f"mu_{element} - mu_{reference}",
            "gauge_invariant_within_fixed_Pt3X_manifold": True,
        }
        if T is not None:
            row["T_K"] = T
        output.append(row)
    return output


def main() -> None:
    csv_path = _resolve_data_csv()
    print(f"Reading 165-point data from:\n  {csv_path}\n")
    df = pd.read_csv(csv_path)
    assert len(df) == 165, f"Expected 165 rows, got {len(df)}"

    h_end, omega, quality = fit_cef(df)

    print("=" * 70)
    print("CEF sublattice fit: end-members (per atom, kJ/mol)")
    print("=" * 70)
    for el in ELEMENTS:
        print(f"  Pt3{el:<2s}:  {h_end[el]:+.4f}")

    print(f"\nFitted Omega_ij (per atom, kJ/mol):")
    for idx, (ei, ej) in enumerate(PAIRS):
        print(f"  {ei}-{ej}:  {omega[idx]:+.4f}")

    print(f"\nFit quality:")
    for k, v in quality.items():
        print(f"  {k}: {v}")

    rows_0K = mu_HEI_per_atom(Y_BETA, h_end, omega, T=0.0)
    df_0K = pd.DataFrame(rows_0K)
    diffusion_0K = pd.DataFrame(beta_diffusion_potentials(rows_0K, T=0.0))

    si_rows: list[dict] = []
    diffusion_T_rows: list[dict] = []
    for T in SI_TEMPERATURES:
        rows_T = mu_HEI_per_atom(Y_BETA, h_end, omega, float(T))
        for r in rows_T:
            r["T_K"] = T
            si_rows.append(r)
        diffusion_T_rows.extend(
            beta_diffusion_potentials(rows_T, T=float(T))
        )
    df_T = pd.DataFrame(si_rows)

    out = Path(__file__).resolve().parent.parent / "outputs"
    out.mkdir(parents=True, exist_ok=True)

    df_0K.to_csv(out / "mu_HEI_v3_0K.csv", index=False, encoding="utf-8")
    df_T.to_csv(out / "mu_HEI_v3_T_table.csv", index=False, encoding="utf-8")
    diffusion_0K.to_csv(
        out / "beta_diffusion_potentials_v3_0K.csv",
        index=False,
        encoding="utf-8",
    )
    pd.DataFrame(diffusion_T_rows).to_csv(
        out / "beta_diffusion_potentials_v3_T_table.csv",
        index=False,
        encoding="utf-8",
    )

    fit_df = pd.DataFrame([
        {
            "pair": f"{ei}-{ej}",
            "omega_per_atom_kJmol": round(float(omega[idx]), 4),
            "Omega_per_beta_site_kJmol": round(4.0 * float(omega[idx]), 4),
            "unit_relation": "omega_per_atom = Omega_per_beta_site / 4",
        }
        for idx, (ei, ej) in enumerate(PAIRS)
    ])
    fit_df.to_csv(out / "omega_beta_subl_v3_fit.csv", index=False, encoding="utf-8")

    pd.DataFrame([quality]).to_csv(
        out / "cef_fit_v3_quality.csv", index=False, encoding="utf-8")

    meta = {
        "script": "script_B_mu_HEI_v3.py",
        "reference": "SER (0 K stable solid = 0)",
        "data_source": str(csv_path),
        "endmember_dH_f_per_atom": {f"Pt3{el}": round(h_end[el], 4) for el in ELEMENTS},
        "omega_ij_per_atom": {f"{ei}-{ej}": round(float(omega[idx]), 4)
                              for idx, (ei, ej) in enumerate(PAIRS)},
        "fit_quality": quality,
        "composition_beta": Y_BETA,
        "element_potential_identifiability": (
            "The fixed-Pt3X manifold determines total G and beta-sublattice "
            "diffusion potentials. Absolute element-resolved potentials require "
            "an additional reference/gauge convention."
        ),
        "legacy_mu_output_convention": (
            "Euler-consistent alloy-atom-normalized decomposition retained for "
            "manuscript regression; do not interpret as unique absolute elemental mu."
        ),
        "diffusion_potential_output": "beta_diffusion_potentials_v3_0K.csv",
        "v3_change": ("End-member ?H_f from UMA 165-pt data, "
                       "Omega_ij from least-squares CEF fit (replaces literature + Miedema)"),
        "convention": "per atom of f.u. (alloy per-atom basis)",
    }
    (out / "script_B_v3_meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")

    print("\n" + "=" * 70)
    print("Script B v3: HEI mu_i (UMA-CEF, SER ref, per atom)")
    print("=" * 70)
    print(df_0K[["element", "sublattice", "y_i",
                  "h_endmember_per_atom_kJmol",
                  "excess_per_atom_kJmol",
                  "mu_HEI_per_atom_kJmol", "note"]].to_string(index=False))
    print("\nGauge-invariant beta-sublattice diffusion potentials")
    print(diffusion_0K.to_string(index=False))
    print(f"\nOutputs -> {out}")


if __name__ == "__main__":
    sys.exit(main() or 0)
