"""
verify_FigB_central.py
======================
Compute the cocktail ΔH_mix and ΔG_mix at 500 K at the canonical
Methods-paragraph-P51 composition for each of the 20 hosts in the
family-grouped Panel b set, using the **corrected Miedema** formula
(see `Panel_f_Wetting/script_FigF_Wetting.py` and
`Panel_a_BinaryHeatmap/regen_FigA_data.py`).

Why this script exists
----------------------
The 800-point scatter CSV that ships with Panel b
(`data_FigB_v2_Long.csv`, 40 perturbation points × 20 hosts) was
generated by an upstream sampling pipeline that is **not** part of
this release. To keep the released code fully reproducible and to
provide a verifiable anchor for the manuscript's central claim
("Pt exhibits the most negative multicomponent mixing enthalpy among
all 20 elements screened" — main text P18), this script regenerates
the central anchor value (no perturbation) for every host and verifies
the ranking explicitly.

If the upstream 40-point sampler is brought into the repository at a
later date it should target the central values printed here, modulo
the Gaussian σ = 0.008 stoichiometric drift documented in Methods
P51.

Method (matches manuscript Methods eq. 1 and the released Panel b anchor)
----------------------------------------------------------------------------
* Canonical screening composition: c_host = 0.25 and
  c_X = 0.75 · y_X, with y_Ga = 0.65, y_In = 0.20, y_Sn = 0.10,
  y_Zn = 0.05. This is the historical Panel b screening anchor; it is not
  the A₃B/Pt₃X product stoichiometry.
* A composition-sensitivity table also evaluates c_host = 0.75, which is the
  A₃B host fraction, so the host ranking can be checked against this choice.
* Binary Miedema (per Methods P47 eq. 1):
      ΔH_AB(50:50) = -P (Δφ*)² + Q (Δn_WS^(1/3))²,
      P = 14.1 kJ V⁻²,  Q = 9.4 kJ (d.u.)⁻²ᐟ³,
  with parameters from shared/data_periodic_table.py (the n_ws
  column already stores n_WS^(1/3); no further cube root).
* Multi-component extrapolation (Methods P47 eq. 2, Hildebrand-
  Muggianu):
      ΔH_mix = Σ_{i<j} 4 c_i c_j · ΔH_ij(50:50).
  Cocktail-internal pair enthalpies (Ga-In, Ga-Sn, Ga-Zn, In-Sn,
  In-Zn, Sn-Zn) are taken from the literature-curated values used
  in SI Table 2/3 (`SI_Figures/SI_Table01_ZnDownSelection/
  script_SI_LiquidusPredictor.py`).
* Ideal configurational entropy (Methods P51):
      ΔS_mix = -R Σ c_i ln c_i,
  added at 500 K so that ΔG_mix = ΔH_mix - T ΔS_mix.

Outputs
-------
data_FigB_central_anchors_regen.csv : 20-row table of central ΔH_mix and
                                      ΔG_mix(500 K) per host, plus host ranking.

Reproducibility: pure NumPy/Pandas; no UMA dependency; deterministic.
"""
from __future__ import annotations
import math
import sys
from itertools import combinations
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "shared"))
from data_periodic_table import periodic_table_data as TBL  # noqa: E402

# Miedema simplified-form constants (Methods P47)
P_KJ_V2, Q_KJ_DU = 14.1, 9.4

# Cocktail internal composition (Methods P51)
Y_X = {"Ga": 0.65, "In": 0.20, "Sn": 0.10, "Zn": 0.05}

# Historical screening anchor used by the released Panel b data. This is not
# the A3B/Pt3X product composition; that case has c_host = 0.75 and is tested
# separately below.
C_HOST = 0.25
SENSITIVITY_C_HOST = (0.25, 0.75)

# Cocktail-internal binary enthalpies (kJ/mol of average atoms at 50:50)
# Literature-curated, identical to H_MIX_BINARY in script_SI_LiquidusPredictor.py
H_MIX_X_X = {
    frozenset(["Ga", "In"]): +0.7,
    frozenset(["Ga", "Sn"]): -1.0,
    frozenset(["Ga", "Zn"]): +3.6,
    frozenset(["In", "Sn"]): +0.4,
    frozenset(["In", "Zn"]): +5.5,
    frozenset(["Sn", "Zn"]): +4.7,
}

# Family-grouped host order (matches Panel_a / Panel_b shipped order)
HOSTS = ["Pt", "Ir", "Pd", "Rh", "Ru", "Os",
         "Ni", "Co", "Fe", "Cr",
         "Re", "Au", "Zr", "W", "Hf", "Mo",
         "Ce", "La", "Y", "Sc"]

R_GAS_KJ = 8.314e-3   # kJ/(mol·K)
T_K = 500.0


def dH_binary_miedema(a: str, b: str) -> float:
    """Simplified Miedema (Methods eq. 1) — table value used directly for n_WS^(1/3)."""
    Ai, Bi = TBL[a], TBL[b]
    dphi = Ai["Phi"] - Bi["Phi"]
    dn = Ai["n_ws"] - Bi["n_ws"]                # n_ws column IS n_WS^(1/3)
    return -P_KJ_V2 * dphi ** 2 + Q_KJ_DU * dn ** 2


def dH_pair(a: str, b: str) -> float:
    """Binary ΔH(a, b) at 50:50 — Miedema for host-X, literature for X-X."""
    pair = frozenset([a, b])
    if a in Y_X and b in Y_X:
        return H_MIX_X_X[pair]
    return dH_binary_miedema(a, b)


def mix_at_composition(host: str, c_host: float) -> tuple[float, float]:
    """Hildebrand-Muggianu ΔH and ΔG(500 K) at composition (c_host + Y_X cocktail)."""
    c = {host: c_host, **{X: (1.0 - c_host) * y for X, y in Y_X.items()}}
    elements = list(c)
    dH = sum(4.0 * c[i] * c[j] * dH_pair(i, j)
             for i, j in combinations(elements, 2))
    dS = -R_GAS_KJ * sum(c[i] * math.log(c[i]) for i in elements if c[i] > 0)
    dG = dH - T_K * dS
    return dH, dG


def main() -> None:
    rows = []
    for host in HOSTS:
        dH, dG = mix_at_composition(host, C_HOST)
        rows.append({"Host": host, "c_host": C_HOST,
                     "dH_mix_kJmol": round(dH, 3),
                     "TdS_500K_kJmol": round(dH - dG, 3),
                     "dG_mix_500K_kJmol": round(dG, 3)})
    df = pd.DataFrame(rows)
    df["dH_rank"] = df["dH_mix_kJmol"].rank(method="dense", ascending=True).astype(int)
    df = df.sort_values("dH_rank")

    out = HERE / "data_FigB_central_anchors_regen.csv"
    df.to_csv(out, index=False)
    print(f"Wrote {out}")
    print("Canonical reference remains data_FigB_central_anchors.csv")
    print(df.to_string(index=False))

    pt = df[df["Host"] == "Pt"].iloc[0]
    assert int(pt["dH_rank"]) == 1, "Manuscript-critical: Pt must be the most-negative cocktail ΔH host"
    print(f"\nVerification: Pt is rank #{int(pt['dH_rank'])} (most negative) — manuscript P18 claim holds.")
    print(f"  Pt cocktail dH_mix(c_host=0.25)  = {pt['dH_mix_kJmol']:+.3f} kJ/mol")
    print(f"  Pt cocktail dG_mix(500 K)        = {pt['dG_mix_500K_kJmol']:+.3f} kJ/mol")

    sensitivity_rows = []
    for c_host in SENSITIVITY_C_HOST:
        for host in HOSTS:
            dH, dG = mix_at_composition(host, c_host)
            sensitivity_rows.append({
                "Host": host,
                "c_host": c_host,
                "composition_role": (
                    "historical_screening_anchor"
                    if c_host == C_HOST else "A3B_host_fraction"
                ),
                "dH_mix_kJmol": dH,
                "dG_mix_500K_kJmol": dG,
            })
    sensitivity = pd.DataFrame(sensitivity_rows)
    sensitivity["dH_rank_within_composition"] = (
        sensitivity.groupby("c_host")["dH_mix_kJmol"]
        .rank(method="dense", ascending=True)
        .astype(int)
    )
    sensitivity = sensitivity.sort_values(
        ["c_host", "dH_rank_within_composition"]
    )
    sensitivity_out = HERE / "data_FigB_composition_sensitivity_regen.csv"
    sensitivity.to_csv(sensitivity_out, index=False, float_format="%.6f")

    for c_host in SENSITIVITY_C_HOST:
        ranked = sensitivity[sensitivity["c_host"] == c_host]
        pt_rank = int(
            ranked.loc[ranked["Host"] == "Pt", "dH_rank_within_composition"].iloc[0]
        )
        assert pt_rank == 1, f"Pt is not rank #1 at c_host={c_host:.2f}"
        top_five = ", ".join(ranked.head(5)["Host"])
        print(
            f"Sensitivity: c_host={c_host:.2f}, Pt rank #{pt_rank}; "
            f"top five = {top_five}"
        )
    print(f"Wrote {sensitivity_out}")


if __name__ == "__main__":
    main()
